### PR TITLE
Add test for shadow dom inside custom html element

### PR DESCRIPTION
**Pull request by elgohr**
Please see https://github.com/playwright-community/playwright-go/issues/307

### CODE REVIEW

**Review by ninadingole — APPROVED** [review]
Lgtm

**Comment by canstand** [comment]
As mentioned in #307, so close this.
> its covered in the upstream Playwright project,

**Comment by elgohr** [comment]
It doesn’t, as you see in the tests

**Comment by canstand** [comment]
`upstream` means tests in https://github.com/microsoft/playwright/blob/ebd0ff9422fb24bf7bdd651ae883b66792ecced9/tests/page/selectors-css.spec.ts#L77, etc.

Testing independent of playwright-go client implementation should be done at https://github.com/microsoft/playwright.

**Comment by elgohr** [comment]
So this folder will be deleted?
https://github.com/playwright-community/playwright-go/tree/main/tests

**Pull request closed without merging**
