### PR TITLE
Roll to playwright v1.30.0

### PR DESCRIPTION
**Pull request by canstand**
This PR upgrades playwright to v1.30.0, a version with less significant changes. Also

- Add APIRequest/APIRequestContext/APIResponse
- Added `timeout` and `predicate` support for several WaitFor or Expect methods

Any feedback and review is welcome and appreciated. Thank you!

### CODE REVIEW

**Comment by ChristianSch** [comment]
@mxschmitt would it be possible to review this?

**Comment by ChristianSch** [comment]
@canstand what about the failing firefox test? any ideas?

**Comment by mxschmitt** [comment]
Great work!

**Comment by canstand** [comment]
@ChristianSch The logs show that it doesn't seem to be a client-side issue. I would prioritize the issues that can be reproduced locally.

**Pull request merged**
