### PR TITLE
chore: roll to Playwright v1.47.0

### PR DESCRIPTION
**Pull request by canstand**

### CODE REVIEW

**Comment by canstand** [comment]
Hi @mxschmitt , Playwright throws an error and exits on certificate mismatch. The difference with the playwright-python test is that the TLS server uses the go standard option `tls.RequireAndVerifyClientCert`.  

Pls take a look at : https://github.com/playwright-community/playwright-go/actions/runs/10465991368/job/28982096640?pr=480#step:6:166

**Comment by mxschmitt** [comment]
Looks indeed like an upstream bug! Let me try to take a look tomorrow. Should be easily reproducible. Thanks for letting me know!

**Comment by mxschmitt** [comment]
@canstand fyi https://github.com/microsoft/playwright/pull/32258 - you might need to wait until this one lands or disable http2 in the tests for now.

**Comment by mxschmitt** [comment]
Please try version `1.47.0-alpha-2024-08-24` which contains a few bug-fixes and seems to fix that specific issue.

**Review by mxschmitt — APPROVED** [review]

**Pull request merged**
